### ISSUE TITLE
Dark Theme issues

### ISSUE THREAD

**Issue by MrJPGames** [MrJPGames/WayFarer-#22]
- Edit icons on settings page still black in dark mode makes them essentially invisible
- Text boxes are also black backgrounds making them harder to see
- Language drop down essentially unreadable black on black

**Comment by DragonBallZeke** [comment]
Additional relevant bug is that the upgrade header is in white text even in light mode, making it only possible to read in dark mode. It should switch to black text when dark mode is disabled.

**Comment by MrJPGames** [comment]
You're correct, this was also reported on Reddit I believe. But I forgot to create a new issue for it. Thanks for reminding me about the issue! Will fix it right away so I won't need to add an issue :)
