### ISSUE TITLE
Broken Google Maps URL while reviewing edits

### ISSUE THREAD

**Issue by nialzinth** [MrJPGames/WayFarer-#27]
Just had two edits where I tried using the 'Open in Google Maps' button. This failed twice as the URL ended with empty parentheses and it just went to my home location. Both cases the URL ended with:
+()

In regular submits this seems to be fine as the parentheses are filled with the submit's title.

**Comment by MrJPGames** [comment]
Thanks for reporting. Should be fixed later today (CEST)!
