### ISSUE TITLE
"What is it?" selector not displayed in Compact View

### ISSUE THREAD

**Issue by tehstone** [MrJPGames/WayFarer-#31]
Perhaps this is intentional, but when in the compact view the "what is it?" selector is not visible.

Ideally this should be visible with either view as it is an important part of reviewing.

**Comment by MrJPGames** [comment]
This feature was developed by @GoncaloCdM, so don't know if it's intentional or not.

I do agree though that this should be included in all views. This issue should be resolved in 1.8.1 later today hopefully.
