### ISSUE TITLE
CTRL-less zooming while reviewing location edits

### ISSUE THREAD

**Issue by nialzinth** [MrJPGames/WayFarer-#36]
Works fine when reviewing nominations but doesn't work when reviewing location edits despite the option being enabled in the settings.

**Comment by MrJPGames** [comment]
Might be due to recent update of the edit review page. This should be an easy fix, as such will be fixed later today!

**Comment by MrJPGames** [comment]
Progress update: Seems to be only the new small map that is affected. The large location edit map seems to already be supported

**Comment by MrJPGames** [comment]
Afaik I did not change code that should have fixed this issue but the small map also works just fine. Closing this issue.

If it was something I changes the change should go live later today so it should truly be fixed.
