### ISSUE TITLE
Marker collision issue on location edits

### ISSUE THREAD

**Issue by nialzinth** [MrJPGames/WayFarer-#37]
The red marker seems to block the dot behind it partially. It's really finicky to pick in this case the left option. I managed to do it in the end but there's only a few pixels room to get the dot selected. Then if you do manage...the green marker (your selection) becomes hidden behind it.
Does NOT prevent you from finishing the review.

![clicking issues](https://user-images.githubusercontent.com/2429173/67852281-6e497d00-fb0c-11e9-8f99-983d0bf1ffcd.jpg)

**Comment by MrJPGames** [comment]
Yes this is "intended". In the sense it's a placeholder before a cleaner solution is implemented.

I will prioritise this in part due to this issue, expect a new approach later today!
