### ISSUE TITLE
[BUG?] When using the new quick submission button on 1 Star > Temporary or Seasonal Display it doesn't work and just refreshes the page

### ISSUE THREAD

**Issue by elamhut** [MrJPGames/WayFarer-#65]
Also, could you add a text to the quick skip button as "Quick Submit"? I was EXTREMELY confused by the addition of that button and a text describing what it does would be great.

Edit: It also doesn't work on Duplicates

**Comment by MrJPGames** [comment]
I assume your using Firefox as this feature is currently only live on Firefox. This should have been fixed in a recent update. I'll investigate if this fix was indeed successful and if not I'll try to fix it ASAP.

**Comment by elamhut** [comment]
Yeah, Firefox, I assumed this feature was live on both, sorry :)

**Comment by MrJPGames** [comment]
Tested on Firefox and seems to work without problems. Could you please specify which version of the add-on you are using.

**Comment by MrJPGames** [comment]
This issue will be closed in 7 days if no further information is provided on how to reproduce the issue. As I am unable to do so currently I will see the bug as already resolved.

**Comment by elamhut** [comment]
Feel free to close the issue, updated the plugin and everything is working on every situation I described above :) Thanks!
