### ISSUE TITLE
[BUG] 'Smearing' of background for localized WF versions

### ISSUE THREAD

**Issue by Dragoncat4** [MrJPGames/WayFarer-#66]
**Describe the bug**
The position of stars is slightly covered by background when somebody is not using English version of WF.

**To Reproduce**
Change language of WF and see yourself. In attached SS it is in Polish.

**Expected behavior**
:)

**Screenshots**
Attached
![Niom](https://user-images.githubusercontent.com/20752913/68883330-7bc05300-0719-11ea-825c-4818a23e26ec.png)

**Browser (please complete the following information):**
FireFox

**Comment by MrJPGames** [comment]
I'm on it :)
Thanks for your report!
