### ISSUE TITLE
Quick submit with keyboard shortcut

### ISSUE THREAD

**Issue by leagueofperez** [MrJPGames/WayFarer-#72]
**Describe the feature you'd like**
Quick submit with keyboard shortcut
**Describe reasons NOT to add this feature**
Use the "Quick submit feature with a desktop shortcut" i.e. if ctrl+enter

**Describe reasons to add this feature**
This would make you to not use the mouse

**Additional context**

**Comment by MrJPGames** [comment]
Use the spacebar
