### ISSUE TITLE
Give what-is-it and additional-comments 50% width in Compact card view

### ISSUE THREAD

**Issue by jonaro00** [MrJPGames/WayFarer-#76]
Title. Makes the compact view more compact. Smaller document height makes scrolling down to the submit button more convenient.
Example:
![image](https://user-images.githubusercontent.com/54029719/69637832-bb603680-1059-11ea-90d4-bd81554bbf8a.png)

**Comment by MrJPGames** [comment]
Seems like a great change! Will be implemented for the next update :)
