### ISSUE TITLE
Preset doesn't apply "What is it? (Optional)" 

### ISSUE THREAD

**Issue by fortepc** [MrJPGames/WayFarer-#77]
**Describe the bug**

**To Reproduce**
1. Save a preset with the "What is it? (Optional)" question answered
2. move on to a new review
3. attempt to use the preset
4. all questions except "What is it? (Optional)" are applied. 

**Expected behavior**
I expect for presets to include the "What is it? (Optional)" question

**Screenshots**

**Browser (please complete the following information):**
e.g. Chrome (if tested on multiple browsers please state all affected)
Only tested on Brave (a fork of Chrome)

**Additional context**

**Comment by MrJPGames** [comment]
This is a know "design" decision. Due to the way the WhatIsIt Box works this functionality is not as easily added as I would like. It's already in the plans to add this at some point though I won't be able to give an ETA for this at the moment.

**Comment by fortepc** [comment]
Well, OPR Tools definitely did this, so you can probably nick the method off then :+1: That's why I considered it a bug, I assumed this was just OPR Tools wrapped in a chrome extension with some minor modifications to be more useful to pogo people.

**Comment by MrJPGames** [comment]
Forgot I had that opened already too... Oops. Well I'll close this duplicate then.
