### ISSUE TITLE
[OPR-TOOLS PARITY REQUEST] Clicking shift should return back to the previous question

### ISSUE THREAD

**Issue by fortepc** [MrJPGames/WayFarer-#78]
title. 

 Clicking shift should return back to the previous question

This is how it worked in the OPR Tools userscript

**Comment by MrJPGames** [comment]
You can use the arrow keys to move between questions. For full controls: https://github.com/MrJPGames/WayFarer-/wiki/Using-keyboard-controls.

I'll close the issue but if this is not what you meant feel free to reopen and clarify!

**Comment by fortepc** [comment]
This is even better! thanks!
