### ISSUE TITLE
Allow for Recon Badge offset

### ISSUE THREAD

**Issue by fortepc** [MrJPGames/WayFarer-#79]
#46 added recon badge status, but failed to take into account that any agreements stats were reset in the switch from OPR to Wayfarer, so my actual Recon badge is at 1,343 (silver) despite Wayfarer saying I've only got 158 (bronze) agreements so far.  

An offset in the settings for the extension to just add the difference back in would be nice.

**Comment by fortepc** [comment]
The way I'd imagine this working, is if the Ingress account is turned on, a new setting appears underneath it just called "Recon Badge Offset" where I can type in 1185 in my case so that it adds 1185 to wayfarer's agreements stat to make the recon badge calculation accurate.

**Comment by MrJPGames** [comment]
I'll add this together with a revamp of the settings as they're getting a little to cluttered right now. I did not know that some peoples stats were reset, but this should be pretty easy to add for those affected!
