### ISSUE TITLE
Missaligned cirlces for nSubCtrl.map

### ISSUE THREAD

**Issue by MrJPGames** [MrJPGames/WayFarer-#8]
Image demonstrating issue: https://m.imgur.com/9yZqCds?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Possible fix use nSubCtrl nomination lonLat instead of map center?

Reproducable? "switching tabs on the left side"

**Comment by JimBim89** [comment]
Might also have to at least zoomed once? If you can't reproduce let me know.

**Comment by MrJPGames** [comment]
I cannot seem to reproduce the issue. I have switched between different pages (tabs on the left side) and back to review and despite panning and zooming, including when the map is still loading does not seem to change this.

I will attempt to fix it anyways as there is probably a cleaner solution than the current one anyways. If you've found a consistent way of reproducing the bug let me know :)

**Comment by JimBim89** [comment]
Rarely happened during regular use, and always in the duplicate view. The screenshot above was panned before it was saved though, normally both circles appear centered and the niantic pin wasn't.

**Comment by MrJPGames** [comment]
That leads me to believe even more that the fix just pushed to the development branch is in fact a real fix.
I will soon be updating store fronts versions as well after the pull request to main is done. So hopefully this bug should no longer occur. Feel free to reopen a issue if it does!
