### ISSUE TITLE
[BUG] Wiki page for shortcuts is missing D for Duplicate

### ISSUE THREAD

**Issue by vibrunazo** [MrJPGames/WayFarer-#81]
The wiki page at [https://github.com/MrJPGames/WayFarer-/wiki/Using-keyboard-controls](https://github.com/MrJPGames/WayFarer-/wiki/Using-keyboard-controls) is missing the shortcut D for Duplicates ^^

**Comment by MrJPGames** [comment]
Thanks for notifying me, I forgot to add it. It's added now!
