### ISSUE TITLE
[BUG] It's possible to use the 0 keyboard shortcut to 1-star reject an edit review.

### ISSUE THREAD

**Issue by fortepc** [MrJPGames/WayFarer-#83]
**Describe the bug**
It's possible to use the 0 keyboard shortcut to "reject" a edit review. This shouldn't be possible and could potentially cause issues that could result in an account being flagged for abuse.

**To Reproduce**
1. Review as usual
2. Come across an edit review
3. Click "0" keyboard shortcut. 
4. Rejection box comes up

**Expected behavior**
It's not possible to "reject" an edit review, so pressing 0 on the edit reviews should do nothing

**Screenshots**
Unable to get screenshot as I forgot to get one and the page timed out

**Browser (please complete the following information):**
Brave (chrome fork)

**Additional context**
If this happens again I'll come back with a screenshot if it's requested.

**Comment by MrJPGames** [comment]
This will be fixed ASAP!
